### ISSUE TITLE
Handle case when `record.exc_info[0]` is None

### ISSUE THREAD

**Issue by jacekbj** [namespace-ee/django-datadog-logger#18]
* Django DataDog Logger version: 0.6.2
* Python version: 3.9
* Operating System: independent

### Description

Adding `exc_info=True` outside of an actual exception context (ex. just calling `logger.error('Foo bar', exc_info=True)`) causes an error in `DataDogJSONFormatter`: https://github.com/namespace-ee/django-datadog-logger/blob/master/django_datadog_logger/formatters/datadog.py#L149. `record.exc_info` in such case is a tuple `(None, None, None)`.

### What I Did

traceback:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/site-packages/json_log_formatter/__init__.py", line 64, in format
    json_record = self.json_record(message, extra, record)
  File "/usr/local/lib/python3.9/site-packages/django_datadog_logger/formatters/datadog.py", line 149, in json_record
    log_entry_dict["error.kind"] = record.exc_info[0].__name__
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by lnagel** [comment]
@jacekbj Thanks for the notice. Would you be willing to draft a PR to handle this?

**Comment by jacekbj** [comment]
@lnagel PR open
